services:
  langchain:
    build: .
    volumes:
      - .:/workspaces/llamachain:cached
    networks:
      - private
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    command: sleep infinity

  ollama:
    image: ollama/ollama:0.1.29
    hostname: ollama
    volumes:
      - ollama:/root/.ollama
    networks:
      - private
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu, utility ]

volumes:
  ollama:


networks:
  private:
